INSERT INTO burgers (burger_name) VALUES ('New Bacon-ings Burger');
INSERT INTO burgers (burger_name) VALUES ('The Tunami Burger');
INSERT INTO burgers (burger_name, devoured) VALUES ('The Mission A-Corn-Plished Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('National Pass-Thyme Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('The Fig-eta Bout It Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Ruta-Bag-A Burger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('I Mint to Do That Burger (comes with mint relish)', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('One Fish, Two Fish, Red Fish Hamburger', true);
INSERT INTO burgers (burger_name, devoured) VALUES ('Grandpa Muenster Burger', true);
INSERT INTO burgers (burger_name) VALUES ('Summer Thyme Burger');
INSERT INTO burgers (burger_name) VALUES ('Peas and Thank You Burger');
INSERT INTO burgers (burger_name) VALUES ('Yes I Cayenne Burger');
INSERT INTO burgers (burger_name) VALUES ('Sweet Home Avocado Burger');
INSERT INTO burgers (burger_name) VALUES ('Butterface Burger (served with butter lettuce)');
INSERT INTO burgers (burger_name) VALUES ('Caper Magic to Yourself (comes with capers, also magic doesnt exist)');
INSERT INTO burgers (burger_name) VALUES ('Beets Me Burger');